services:
  postgre-sql:
    image: postgres:16.4
    restart: always
    networks:
      - odoo-net
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=JXPF9aDZeZWlrDpf
    volumes:
      # Persist data for the production PostgreSQL instance
      - db-data:/var/lib/postgresql/data

  odoo:
    build: .
    restart: always
    depends_on:
      - postgre-sql
    networks:
      - odoo-net
    ports:
      - "8069:8069"
    environment:
      # PostgreSQL Development Environment Variables
      - POSTGRES_HOST=postgre-sql
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=JXPF9aDZeZWlrDpf
    volumes:
      # Persist logs for the production Odoo instance
      - ./logs:/var/log/odoo


networks:
  odoo-net:
    driver: bridge

volumes:
  # Volumes for persisting database data
  db-data:


