services:
  postgresql:
    image: postgres:16.4
    restart: always
    networks:
      - odoo-net
    environment:
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=JXPF9aDZeZWlrDpf
    volumes:
      # Persist data for the production PostgreSQL instance
      - db-data:/var/lib/postgresql/data

  odoo:
    build: .
    restart: always
    depends_on:
      - postgresql
    networks:
      - odoo-net
    ports:
      - "8069:8069" # Expose Odoo's main HTTP service port for accessing the web interface.
      - "8071:8071" # Expose XML-RPC over HTTPS for secure external integrations.
      - "8072:8072" # Expose long-polling port for real-time features like chat notifications.
    environment:
      # PostgreSQL Development Environment Variables
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=odoo_db
      - POSTGRES_USER=odoo_user
      - POSTGRES_PASSWORD=JXPF9aDZeZWlrDpf
    volumes:
      # Persist logs for the production Odoo instance
      - ./odoo-data:/var/lib/odoo


networks:
  odoo-net:
    driver: bridge

volumes:
  # Volumes for persisting database data
  db-data:


